version: "3.9"

services:
  terraform:
    image: hashicorp/terraform:1.5
    platform: linux/arm/v6
    volumes:
      - ./terraform:/usr/src/terraform
    environment:
      - TF_LOG=TRACE
      - TF_LOG_PATH=./terraform.log
    env_file: docker.env
    command: "/bin/bash"
    entrypoint: ""
    working_dir: /usr/src/terraform/envs
